# Generated by Django 5.2 on 2025-10-14 05:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('tipo_ingreso', models.CharField(choices=[('anticipo', 'Anticipo'), ('pago_avance', 'Pago por Avance'), ('pago_final', 'Pago Final'), ('ingreso_adicional', 'Ingreso Adicional'), ('ajuste_contractual', 'Ajuste Contractual'), ('otro', 'Otro')], default='pago_avance', max_length=25, verbose_name='Tipo de ingreso')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto total')),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto recibido')),
                ('fecha_esperada', models.DateField(verbose_name='Fecha esperada')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('parcial', 'Parcial'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('metodo_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Método de pago')),
                ('numero_referencia', models.CharField(blank=True, max_length=100, verbose_name='Número de referencia/factura')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100, verbose_name='Cuenta bancaria')),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='finanzas/ingresos/%Y/%m/', verbose_name='Documento de soporte')),
                ('relacionado_con_avance', models.BooleanField(default=False, verbose_name='Relacionado con avance de obra')),
                ('porcentaje_avance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de avance asociado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='proyectos.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'finanzas_ingresos',
                'ordering': ['-fecha_esperada', '-creado_en'],
                'indexes': [models.Index(fields=['proyecto', 'estado'], name='finanzas_in_proyect_0ee675_idx'), models.Index(fields=['fecha_esperada'], name='finanzas_in_fecha_e_3d7d04_idx'), models.Index(fields=['fecha_recepcion'], name='finanzas_in_fecha_r_e40ee1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('materiales', 'Materiales'), ('mano_obra', 'Mano de Obra'), ('equipo', 'Equipo y Maquinaria'), ('subcontratos', 'Subcontratos'), ('administrativos', 'Gastos Administrativos'), ('indirectos', 'Costos Indirectos'), ('contingencia', 'Contingencia'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('subcategoria', models.CharField(blank=True, max_length=100, verbose_name='Subcategoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto_planeado', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto planeado')),
                ('monto_comprometido', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto comprometido')),
                ('monto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto gastado')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio del período')),
                ('periodo_fin', models.DateField(verbose_name='Fin del período')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='proyectos.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'finanzas_presupuestos',
                'ordering': ['categoria', 'periodo_inicio'],
                'indexes': [models.Index(fields=['proyecto', 'categoria'], name='finanzas_pr_proyect_e77aeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionFlujoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(12)], verbose_name='Mes')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('ingresos_proyectados', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos proyectados')),
                ('egresos_proyectados', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Egresos proyectados')),
                ('ingresos_reales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos reales')),
                ('egresos_reales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Egresos reales')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo inicial')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo final')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones_flujo_caja', to='proyectos.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Proyección de Flujo de Caja',
                'verbose_name_plural': 'Proyecciones de Flujo de Caja',
                'db_table': 'finanzas_proyecciones_flujo_caja',
                'ordering': ['año', 'mes'],
                'unique_together': {('proyecto', 'mes', 'año')},
            },
        ),
    ]
