# Generated by Django 5.2.7 on 2025-10-26 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('tipo_egreso', models.CharField(choices=[('material', 'Material'), ('mano_obra', 'Mano de Obra'), ('subcontrato', 'Subcontrato'), ('equipo', 'Equipo y Maquinaria'), ('administrativo', 'Gasto Administrativo'), ('servicio', 'Servicio'), ('transporte', 'Transporte'), ('impuesto', 'Impuesto'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de egreso')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor/Beneficiario')),
                ('nit_proveedor', models.CharField(blank=True, max_length=50, verbose_name='NIT/RUT del proveedor')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto pagado')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('metodo_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Método de pago')),
                ('numero_factura', models.CharField(blank=True, max_length=100, verbose_name='Número de factura')),
                ('numero_orden_compra', models.CharField(blank=True, max_length=100, verbose_name='Número de orden de compra')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100, verbose_name='Cuenta bancaria destino')),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='finanzas/egresos/%Y/%m/', verbose_name='Documento de soporte')),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retención IVA')),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retención en la fuente')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='finanzas.presupuesto', verbose_name='Presupuesto asociado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='proyectos.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'db_table': 'finanzas_egresos',
                'ordering': ['-fecha_vencimiento', '-creado_en'],
                'indexes': [models.Index(fields=['proyecto', 'estado'], name='finanzas_eg_proyect_b407b4_idx'), models.Index(fields=['fecha_vencimiento'], name='finanzas_eg_fecha_v_a84c46_idx'), models.Index(fields=['fecha_pago'], name='finanzas_eg_fecha_p_9741ce_idx'), models.Index(fields=['tipo_egreso'], name='finanzas_eg_tipo_eg_86f76d_idx'), models.Index(fields=['proveedor'], name='finanzas_eg_proveed_2a80ee_idx')],
            },
        ),
    ]
