# Generated by Django 5.2 on 2025-10-06 20:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del proyecto')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='Empresa del cliente')),
                ('location', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha real de inicio')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha real de fin')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto del contrato')),
                ('contract_type', models.CharField(choices=[('fixed_price', 'Precio Fijo'), ('time_material', 'Tiempo y Material'), ('cost_plus', 'Costo Más Honorarios')], default='fixed_price', max_length=20, verbose_name='Tipo de contrato')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto asignado')),
                ('status', models.CharField(choices=[('planning', 'En Planificación'), ('active', 'Activo'), ('on_hold', 'En Pausa'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='planning', max_length=20, verbose_name='Estado')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('document_type', models.CharField(choices=[('contract', 'Contrato'), ('blueprint', 'Plano'), ('permit', 'Permiso'), ('report', 'Reporte'), ('other', 'Otro')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='proyectos/documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proyectos.project')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'proyectos_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Gerente'), ('supervisor', 'Supervisor'), ('engineer', 'Ingeniero'), ('foreman', 'Capataz'), ('accountant', 'Contador'), ('assistant', 'Asistente')], max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_approve_payments', models.BooleanField(default=False)),
                ('can_manage_payroll', models.BooleanField(default=False)),
                ('can_view_financials', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='proyectos.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
                'db_table': 'proyectos_project_team',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'start_date'], name='proyectos_p_status_c7ff04_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by', 'created_at'], name='proyectos_p_created_bc31e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together={('project', 'user')},
        ),
    ]
